org: danny1robinson
app: synopsis
service: lambdas
frameworkVersion: '3'
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-west-2

functions:
  fileupload:
    handler: index.handler
    timeout: 30
    events:
    - http:
        path: /fileupload
        method: post
        cors: true
  read:
    handler: read.handler
    timeout: 30
    events:
    - http:
        path: /readfile
        method: post
        cors: true
  chat:
    handler: chat.chat
    timeout: 30
    events:
    - http:
        path: /chat
        method: post
        cors: true
    - http:
        path: /chat
        method: get
        cors: true
  report:
    handler: report.report
    timeout: 30
    events:
    - http:
        path: /report
        method: post
        cors: true
    - http:
        path: /report
        method: get
        cors: true